filegroup(
    name = "test_health_manager_data_yaml",
    srcs = [
        "test_health_manager_data.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_health_modules_yaml",
    srcs = [
        "test_health_modules.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_library_data_yaml",
    srcs = [
        "test_status_effect_library_data.yaml",
    ],
    visibility = ["//visibility:public"],
)
