load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "base_module",
    srcs = ["base_module.cpp"],
    hdrs = ["base_module.h"],
    deps = [
        "//code/client/modules/descriptors/base:base_descriptor",
    ],
    visibility = ["//visibility:public"],
)
