filegroup(
    name = "test_damage_type_descriptor_base_yaml",
    srcs = [
        "damage_type.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_heal_type_descriptor_base_yaml",
    srcs = [
        "heal_type.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_descriptor_base_yaml",
    srcs = [
        "status_effect.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_library_data_yaml",
    srcs = [
        "status_effect_lib.yaml",
    ],
    visibility = ["//visibility:public"],
)
