// [START declaration]
syntax = "proto3";
package code.client.messages;
// [END declaration]

// [START messages]
message Heal {
  enum HealType {
    NONE = 0;
    POTION = 1;   // 1 << 0
    MAGIC = 2;    // 1 << 1
    HOLY = 4;     // 1 << 2
    ALL = 7;      // 111   Update as needed and must be last
  }

  int32 heal_type = 1;
  float amount = 2;
  repeated string status_effect = 3; // optional application of status effects

  string heal_source_uuid = 4;  // where this healing is coming from
}
// [END messages]
