filegroup(
    name = "test_damage_type_descriptor_yaml",
    srcs = [
        "test_damage_type_descriptor.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_heal_type_descriptor_yaml",
    srcs = [
        "test_heal_type_descriptor.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_descriptor_yaml",
    srcs = [
        "test_status_effect_descriptor.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_library_data_yaml",
    srcs = [
        "test_status_effect_library_data.yaml",
    ],
    visibility = ["//visibility:public"],
)
