filegroup(
    name = "test_module_factory_data_yaml",
    srcs = [
        "test_module_factory_data.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_library_data_yaml",
    srcs = [
        "test_status_effect_library_data.yaml",
    ],
    visibility = ["//visibility:public"],
)
