filegroup(
    name = "test_effect_clear_data_yaml",
    srcs = [
        "test_effect_clear_data.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_effect_damage_data_yaml",
    srcs = [
        "test_effect_damage_data.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_effect_damage_multiply_data_yaml",
    srcs = [
        "test_effect_damage_multiply_data.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_effect_heal_data_yaml",
    srcs = [
        "test_effect_heal_data.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_effect_heal_multiply_data_yaml",
    srcs = [
        "test_effect_heal_multiply_data.yaml",
    ],
    visibility = ["//visibility:public"],
)
