filegroup(
    name = "test_damage_type_apply_module_yaml",
    srcs = [
        "test_damage_type_apply_module.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_apply_module_yaml",
    srcs = [
        "test_status_effect_apply_module.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_library_data_yaml",
    srcs = [
        "test_status_effect_library_data.yaml",
    ],
    visibility = ["//visibility:public"],
)
