filegroup(
    name = "test_damage_type_resist_module_yaml",
    srcs = [
        "test_damage_type_resist_module.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_heal_type_increase_module_yaml",
    srcs = [
        "test_heal_type_increase_module.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_immune_module_yaml",
    srcs = [
        "test_status_effect_immune_module.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_library_data_yaml",
    srcs = [
        "test_status_effect_library_data.yaml",
    ],
    visibility = ["//visibility:public"],
)
