filegroup(
    name = "test_damage_type_module_common_yaml",
    srcs = [
        "test_damage_type_module_common.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_heal_type_module_common_yaml",
    srcs = [
        "test_heal_type_module_common.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_module_common_yaml",
    srcs = [
        "test_status_effect_module_common.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_status_effect_library_data_yaml",
    srcs = [
        "test_status_effect_library_data.yaml",
    ],
    visibility = ["//visibility:public"],
)
